Homework.Web/Models/ErrorViewModel.cs
namespace Homework.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Homework.Web/Models/ProductsViewModel.cs
namespace Homework.Web.Models
{
    public class ProductsViewModel
    {
        public List<Product> Products { get; set; } = new List<Product>();
        public string? TrendingProduct { get; set; }

        public class Product
        {
            public string Title { get; set; } = string.Empty;
            public int Price { get; set; }
            public float DiscountPercentage { get; set; }
            public float Rating { get; set; }
            public string Brand { get; set; } = string.Empty;
            public string Currency { get; set; } = "€";
        }

        public void AddProductToList(string title, int price, float discount, float rating, string brand)
        {
            Products.Add(new Product() 
            { 
                Title = title,
                Price = price,
                DiscountPercentage = discount,
                Rating = rating,
                Brand = brand
            });
        }
    }
}

Homework.Web/Controllers/ProductsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Homework.Web.Models;
using Homework.Web.Services;
using Homework.Web.Services.Interfaces;
using Homework.Web.Data;

namespace Homework.Web.Controllers;

public class ProductsController : Controller
{
    private readonly ILogger<ProductsController> _logger;
    private readonly IProductService _productService;

    public ProductsController(ILogger<ProductsController> logger, IProductService productService)
    {
        _logger = logger;
        _productService = productService;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            var productDto = await _productService.GetAllProductsAsync();
            var viewModel = new ProductsViewModel()
            {
                TrendingProduct = productDto.Products
                .Where(product => product.DiscountPercentage >= 10)
                .OrderByDescending(product => product.Rating)
                .Select(product => product.Title)
                .FirstOrDefault()
            };

            foreach (var item in productDto.Products.Where(product => product.DiscountPercentage >= 10))
            {
                viewModel.AddProductToList(item.Title, item.Price, item.DiscountPercentage, item.Rating, item.Brand);
            }

            return View(viewModel);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, "Error when mapping products to view");
            return View(new ProductsViewModel());
        }
        
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Homework.Web/Views/Home/Index.cshtml
@model Homework.Web.Models.ProductModel

@{
    ViewData["Title"] = "Products listing";
}

<div class="text-center">
    <h1 class="page-title">Products</h1>
    <div class="product-view-utilities-container">
        <div class="trending-product-container">
            <strong>Trending product:</strong>
                @if (Model.Products != null)
                {
                    <span id="trending-product">@Model.Products.OrderBy(product => product.Rating).Where(product => product.DiscountPercentage>=10).Select(product => product.Title).First()</span>
                }
                else
                {
                    <span id="trending-product-error">Unable to fetch trending products...</span>
                }
        </div>
        <div class="product-search-container">
            <input type="text" id="product-search-box" name="ProductFilterString" placeholder="Search..." />
        </div>
    </div>
    @if (Model.Products != null)
    {
        <div class="product-listing-cards">
            @foreach (var product in Model.Products.Where(product => product.DiscountPercentage >= 10).Select((item, index) => new { index, item }))
            {
                <div class="product-card">
                    <div class="product-card-text-container">
                        <div class="card-text-title">
                            <span id="product-@product.index-title">@product.item.Title</span>
                        </div>
                        <div class="card-text-info">
                            <span id="product-@product.index-brand">@product.item.Brand</span>
                            <span id="product-@product.index-price">@product.item.Price €</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <div class="no-products-available">
            <span id="no-products-available-message">Uh oh... It looks like we are unable to offer products at the moment!</span>
        </div>
    }
</div>

Homework.Web/Views/Products/Index.cshtml
@model ProductsViewModel

@{
    ViewData["Title"] = "Products listing";
}

<div class="text-center">
    <h1 class="page-title">Products</h1>
    <div class="product-view-utilities-container">
        @await Html.PartialAsync("_TrendingProduct", Model)
        <div class="product-search-container">
            <input type="text" id="product-search-box" name="ProductFilterString" placeholder="Search..." />
        </div>
    </div>
    @if (Model.Products.Any())
    {
        <div class="product-listing-cards">
            @foreach (var product in Model.Products)
            {
                @await Html.PartialAsync("_ProductCard", product)
            }
        </div>
    }
    else
    {
        <div class="no-products-available">
            <span id="no-products-available-message">Unable to offer products at the moment!</span>
        </div>
    }
</div>

Homework.Web/Views/Products/_ProductCard.cshtml
@model ProductsViewModel.Product

<div class="product-card">
    <div class="product-card-text-container">
        <div class="card-text-title">
            <span>@Model.Title</span>
        </div>
        <div class="card-text-info">
            <span>@Model.Brand</span>
            <span>@Model.Price @Model.Currency</span>
        </div>
    </div>
</div>

Homework.Web/Views/Products/_TrendingProduct.cshtml
@model ProductsViewModel

<div class="trending-product-container">
    <strong>Trending product:</strong>
    @if (!string.IsNullOrEmpty(Model.TrendingProduct))
    {
        <span id="trending-product">@Model.TrendingProduct</span>
    }
    else
    {
        <span id="trending-product-error">Unable to show trending product</span>
    }
</div>

Homework.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeworkMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Homework.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">HomeworkMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">&copy; 2023 - Tomi Salomaa</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>